services:
  db:
    image: postgres:17.2-alpine3.21
    environment:
      - TZ=Asia/Tokyo
    ports:
      - 15432:5432
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
    driver: local
